server:
  port: 8080

coap:
  port: 5683
  oscore:
    enabled: true
    master-secret: "0102030405060708090A0B0C0D0E0F10"  # hex
    master-salt:   "9E7CA92223786340"                  # hex (optional)
    server-sender-id-hex: "02"
    server-recipient-id-hex: "01"

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

logging:
  level:
    # ìš°ë¦¬ íŒ¨í‚¤ì§€(ë¡œê·¸ ì°ëŠ” ê³³)
    com.sp.securityprotocol: DEBUG

    # Californium í•µì‹¬
    org.eclipse.californium: INFO
    org.eclipse.californium.elements: DEBUG

    # ğŸ” ì§ë ¬í™”(UDP ë°”ì´íŠ¸ ë§Œë“¤ê¸° ì§ì „ ìƒíƒœ)
    org.eclipse.californium.core.network.serialization: TRACE

    # ğŸ” ë§¤ì¹­/ì‹ ë¢°/ìŠ¤íƒ ê²½ë¡œ (Type/MID/Tokenì´ ì–¸ì œ ì…‹ì—…ë˜ëŠ”ì§€ í™•ì¸)
    org.eclipse.californium.core.network.matcher: TRACE
    org.eclipse.californium.core.network.stack.ReliabilityLayer: TRACE
    org.eclipse.californium.core.network.stack.BaseCoapStack: TRACE
    org.eclipse.californium.core.network.CoapEndpoint: TRACE

    # ğŸ” OSCORE ë ˆì´ì–´ íë¦„
    org.eclipse.californium.oscore: TRACE
